[package]
name = "cardinal-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Error types and helpers for the Cardinal project"
keywords = ["cardinal", "errors", "error-handling"]
categories = ["development-tools"]

[dependencies]
pingora = { workspace = true, features = ["openssl"] }
cardinal-base = { path = "../base" }
tracing.workspace = true
http.workspace = true
cardinal-errors = { path = "../errors" }
cardinal-filters = { path = "../filters" }
async-trait.workspace = true