name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash
jobs:

  just:
    strategy:
      fail-fast: false
      matrix:
        target: [fmt-check, clippy, cargo-test]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config \
            libssl-dev zlib1g-dev \
            clang libclang-dev \
            libunwind-dev

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'ci-cache'

      - name: Set up just runner
        uses: extractions/setup-just@v2

      - name: Install tools
        run: just install-tools

      - name: Run +${{ matrix.target }}
        run: just ${{ matrix.target }}
