name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.release.draft == false && github.event.release.prerelease == false
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config \
            libssl-dev zlib1g-dev \
            clang libclang-dev \
            libunwind-dev

      - name: Publish crates to crates.io
        run: |
          set -euxo pipefail
          crates=(
            cardinal-config
            cardinal-errors
            cardinal-base
            cardinal-wasm-plugins
            cardinal-plugins
            cardinal-proxy
            cardinal
            cardinal-cli
          )
          for crate in "${crates[@]}"; do
            cargo publish --package "$crate" --locked
            # allow the crates.io index to catch up before the next publish
            sleep 20
          done
